disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
included:
  - swiftwing
excluded:
  - Carthage
  - Pods
  - DerivedData
  - build
line_length:
  warning: 120
  error: 150
identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - db
